package service;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.2.1
 * 2018-06-10T18:27:29.994+03:00
 * Generated source version: 3.2.1
 * 
 */
@WebServiceClient(name = "OrderProcess", 
                  wsdlLocation = "http://localhost:8888/v1/order?wsdl",
                  targetNamespace = "http://localhost:8888/v1/order") 
public class OrderProcess extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://localhost:8888/v1/order", "OrderProcess");
    public final static QName OrderProcessPort = new QName("http://localhost:8888/v1/order", "OrderProcessPort");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost:8888/v1/order?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(OrderProcess.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://localhost:8888/v1/order?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public OrderProcess(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public OrderProcess(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public OrderProcess() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    public OrderProcess(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public OrderProcess(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public OrderProcess(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    




    /**
     *
     * @return
     *     returns OrderProcessService
     */
    @WebEndpoint(name = "OrderProcessPort")
    public OrderProcessService getOrderProcessPort() {
        return super.getPort(OrderProcessPort, OrderProcessService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns OrderProcessService
     */
    @WebEndpoint(name = "OrderProcessPort")
    public OrderProcessService getOrderProcessPort(WebServiceFeature... features) {
        return super.getPort(OrderProcessPort, OrderProcessService.class, features);
    }

}
