package service;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.2.1
 * 2018-06-10T18:27:29.966+03:00
 * Generated source version: 3.2.1
 * 
 */
@WebService(targetNamespace = "http://localhost:8888/v1/order", name = "OrderProcessService")
@XmlSeeAlso({ObjectFactory.class})
public interface OrderProcessService {

    @WebMethod
    @Action(input = "http://localhost:8888/v1/order/OrderProcessService/processOrderRequest", output = "http://localhost:8888/v1/order/OrderProcessService/processOrderResponse")
    @RequestWrapper(localName = "processOrder", targetNamespace = "http://localhost:8888/v1/order", className = "service.ProcessOrder")
    @ResponseWrapper(localName = "processOrderResponse", targetNamespace = "http://localhost:8888/v1/order", className = "service.ProcessOrderResponse")
    @WebResult(name = "return", targetNamespace = "")
    public service.Order processOrder(
        @WebParam(name = "arg0", targetNamespace = "")
        service.Order arg0
    );
}
